# tflm_sources.mk — TensorFlow Lite Micro (lib/pico-tflmicro) のソース一覧
#   lib/pico-tflmicro/CMakeLists.txt の pico-tflmicro ライブラリから、pico-sdk に依存する
#   micro_time.cpp / system_setup.cpp (tflm_port.cpp で代替) と、デュアルコア処理が有効な
#   arm_nn_mat_mult_nt_t_s8.c (tflm.mk で無効にしたものを作る)、画像の推論には使わない
#   音声処理 (src/signal、kissfft) を除いたもの。

TFLM_SRCS := \
	src/tensorflow/compiler/mlir/lite/core/api/error_reporter.cpp \
	src/tensorflow/compiler/mlir/lite/schema/schema_utils.cpp \
	src/tensorflow/lite/core/api/flatbuffer_conversions.cpp \
	src/tensorflow/lite/core/api/tensor_utils.cpp \
	src/tensorflow/lite/core/c/common.cpp \
	src/tensorflow/lite/kernels/internal/common.cpp \
	src/tensorflow/lite/kernels/internal/portable_tensor_utils.cpp \
	src/tensorflow/lite/kernels/internal/quantization_util.cpp \
	src/tensorflow/lite/kernels/internal/reference/comparisons.cpp \
	src/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cpp \
	src/tensorflow/lite/kernels/internal/runtime_shape.cpp \
	src/tensorflow/lite/kernels/internal/tensor_ctypes.cpp \
	src/tensorflow/lite/kernels/internal/tensor_utils.cpp \
	src/tensorflow/lite/kernels/kernel_util.cpp \
	src/tensorflow/lite/micro/arena_allocator/non_persistent_arena_buffer_allocator.cpp \
	src/tensorflow/lite/micro/arena_allocator/persistent_arena_buffer_allocator.cpp \
	src/tensorflow/lite/micro/arena_allocator/recording_single_arena_buffer_allocator.cpp \
	src/tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.cpp \
	src/tensorflow/lite/micro/debug_log.cpp \
	src/tensorflow/lite/micro/fake_micro_context.cpp \
	src/tensorflow/lite/micro/flatbuffer_utils.cpp \
	src/tensorflow/lite/micro/hexdump.cpp \
	src/tensorflow/lite/micro/kernels/activations.cpp \
	src/tensorflow/lite/micro/kernels/activations_common.cpp \
	src/tensorflow/lite/micro/kernels/add_common.cpp \
	src/tensorflow/lite/micro/kernels/add_n.cpp \
	src/tensorflow/lite/micro/kernels/arg_min_max.cpp \
	src/tensorflow/lite/micro/kernels/assign_variable.cpp \
	src/tensorflow/lite/micro/kernels/batch_to_space_nd.cpp \
	src/tensorflow/lite/micro/kernels/broadcast_args.cpp \
	src/tensorflow/lite/micro/kernels/broadcast_to.cpp \
	src/tensorflow/lite/micro/kernels/call_once.cpp \
	src/tensorflow/lite/micro/kernels/cast.cpp \
	src/tensorflow/lite/micro/kernels/ceil.cpp \
	src/tensorflow/lite/micro/kernels/circular_buffer.cpp \
	src/tensorflow/lite/micro/kernels/circular_buffer_common.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/add.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/batch_matmul.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/conv.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/depthwise_conv.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/mul.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/pooling.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/softmax.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/svdf.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/transpose_conv.cpp \
	src/tensorflow/lite/micro/kernels/cmsis_nn/unidirectional_sequence_lstm.cpp \
	src/tensorflow/lite/micro/kernels/comparisons.cpp \
	src/tensorflow/lite/micro/kernels/concatenation.cpp \
	src/tensorflow/lite/micro/kernels/conv_common.cpp \
	src/tensorflow/lite/micro/kernels/cumsum.cpp \
	src/tensorflow/lite/micro/kernels/decompress.cpp \
	src/tensorflow/lite/micro/kernels/decompress_common.cpp \
	src/tensorflow/lite/micro/kernels/depth_to_space.cpp \
	src/tensorflow/lite/micro/kernels/depthwise_conv_common.cpp \
	src/tensorflow/lite/micro/kernels/dequantize.cpp \
	src/tensorflow/lite/micro/kernels/dequantize_common.cpp \
	src/tensorflow/lite/micro/kernels/detection_postprocess.cpp \
	src/tensorflow/lite/micro/kernels/div.cpp \
	src/tensorflow/lite/micro/kernels/elementwise.cpp \
	src/tensorflow/lite/micro/kernels/elu.cpp \
	src/tensorflow/lite/micro/kernels/embedding_lookup.cpp \
	src/tensorflow/lite/micro/kernels/ethosu.cpp \
	src/tensorflow/lite/micro/kernels/exp.cpp \
	src/tensorflow/lite/micro/kernels/expand_dims.cpp \
	src/tensorflow/lite/micro/kernels/fill.cpp \
	src/tensorflow/lite/micro/kernels/floor.cpp \
	src/tensorflow/lite/micro/kernels/floor_div.cpp \
	src/tensorflow/lite/micro/kernels/floor_mod.cpp \
	src/tensorflow/lite/micro/kernels/fully_connected_common.cpp \
	src/tensorflow/lite/micro/kernels/gather.cpp \
	src/tensorflow/lite/micro/kernels/gather_nd.cpp \
	src/tensorflow/lite/micro/kernels/hard_swish.cpp \
	src/tensorflow/lite/micro/kernels/hard_swish_common.cpp \
	src/tensorflow/lite/micro/kernels/if.cpp \
	src/tensorflow/lite/micro/kernels/kernel_runner.cpp \
	src/tensorflow/lite/micro/kernels/kernel_util.cpp \
	src/tensorflow/lite/micro/kernels/l2_pool_2d.cpp \
	src/tensorflow/lite/micro/kernels/l2norm.cpp \
	src/tensorflow/lite/micro/kernels/leaky_relu.cpp \
	src/tensorflow/lite/micro/kernels/leaky_relu_common.cpp \
	src/tensorflow/lite/micro/kernels/log_softmax.cpp \
	src/tensorflow/lite/micro/kernels/logical.cpp \
	src/tensorflow/lite/micro/kernels/logical_common.cpp \
	src/tensorflow/lite/micro/kernels/logistic.cpp \
	src/tensorflow/lite/micro/kernels/logistic_common.cpp \
	src/tensorflow/lite/micro/kernels/lstm_eval.cpp \
	src/tensorflow/lite/micro/kernels/lstm_eval_common.cpp \
	src/tensorflow/lite/micro/kernels/maximum_minimum.cpp \
	src/tensorflow/lite/micro/kernels/micro_tensor_utils.cpp \
	src/tensorflow/lite/micro/kernels/mirror_pad.cpp \
	src/tensorflow/lite/micro/kernels/mul_common.cpp \
	src/tensorflow/lite/micro/kernels/neg.cpp \
	src/tensorflow/lite/micro/kernels/pack.cpp \
	src/tensorflow/lite/micro/kernels/pad.cpp \
	src/tensorflow/lite/micro/kernels/pooling_common.cpp \
	src/tensorflow/lite/micro/kernels/prelu.cpp \
	src/tensorflow/lite/micro/kernels/prelu_common.cpp \
	src/tensorflow/lite/micro/kernels/quantize.cpp \
	src/tensorflow/lite/micro/kernels/quantize_common.cpp \
	src/tensorflow/lite/micro/kernels/read_variable.cpp \
	src/tensorflow/lite/micro/kernels/reduce.cpp \
	src/tensorflow/lite/micro/kernels/reduce_common.cpp \
	src/tensorflow/lite/micro/kernels/reshape.cpp \
	src/tensorflow/lite/micro/kernels/reshape_common.cpp \
	src/tensorflow/lite/micro/kernels/resize_bilinear.cpp \
	src/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cpp \
	src/tensorflow/lite/micro/kernels/round.cpp \
	src/tensorflow/lite/micro/kernels/select.cpp \
	src/tensorflow/lite/micro/kernels/shape.cpp \
	src/tensorflow/lite/micro/kernels/slice.cpp \
	src/tensorflow/lite/micro/kernels/softmax_common.cpp \
	src/tensorflow/lite/micro/kernels/space_to_batch_nd.cpp \
	src/tensorflow/lite/micro/kernels/space_to_depth.cpp \
	src/tensorflow/lite/micro/kernels/split.cpp \
	src/tensorflow/lite/micro/kernels/split_v.cpp \
	src/tensorflow/lite/micro/kernels/squared_difference.cpp \
	src/tensorflow/lite/micro/kernels/squeeze.cpp \
	src/tensorflow/lite/micro/kernels/strided_slice.cpp \
	src/tensorflow/lite/micro/kernels/strided_slice_common.cpp \
	src/tensorflow/lite/micro/kernels/sub.cpp \
	src/tensorflow/lite/micro/kernels/sub_common.cpp \
	src/tensorflow/lite/micro/kernels/svdf_common.cpp \
	src/tensorflow/lite/micro/kernels/tanh.cpp \
	src/tensorflow/lite/micro/kernels/transpose.cpp \
	src/tensorflow/lite/micro/kernels/unpack.cpp \
	src/tensorflow/lite/micro/kernels/var_handle.cpp \
	src/tensorflow/lite/micro/kernels/while.cpp \
	src/tensorflow/lite/micro/kernels/zeros_like.cpp \
	src/tensorflow/lite/micro/memory_helpers.cpp \
	src/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cpp \
	src/tensorflow/lite/micro/memory_planner/linear_memory_planner.cpp \
	src/tensorflow/lite/micro/memory_planner/non_persistent_buffer_planner_shim.cpp \
	src/tensorflow/lite/micro/micro_allocation_info.cpp \
	src/tensorflow/lite/micro/micro_allocator.cpp \
	src/tensorflow/lite/micro/micro_context.cpp \
	src/tensorflow/lite/micro/micro_interpreter.cpp \
	src/tensorflow/lite/micro/micro_interpreter_context.cpp \
	src/tensorflow/lite/micro/micro_interpreter_graph.cpp \
	src/tensorflow/lite/micro/micro_log.cpp \
	src/tensorflow/lite/micro/micro_op_resolver.cpp \
	src/tensorflow/lite/micro/micro_profiler.cpp \
	src/tensorflow/lite/micro/micro_resource_variable.cpp \
	src/tensorflow/lite/micro/micro_utils.cpp \
	src/tensorflow/lite/micro/mock_micro_graph.cpp \
	src/tensorflow/lite/micro/recording_micro_allocator.cpp \
	src/tensorflow/lite/micro/test_helper_custom_ops.cpp \
	src/tensorflow/lite/micro/test_helpers.cpp \
	src/tensorflow/lite/micro/tflite_bridge/flatbuffer_conversions_bridge.cpp \
	src/tensorflow/lite/micro/tflite_bridge/micro_error_reporter.cpp \
	src/third_party/cmsis_nn/Source/ActivationFunctions/arm_nn_activation_s16.c \
	src/third_party/cmsis_nn/Source/ActivationFunctions/arm_relu6_s8.c \
	src/third_party/cmsis_nn/Source/ActivationFunctions/arm_relu_q15.c \
	src/third_party/cmsis_nn/Source/ActivationFunctions/arm_relu_q7.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_add_s16.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_add_s8.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_mul_acc_s16.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_mul_s16.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_mul_s16_batch_offset.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_mul_s16_s8.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_elementwise_mul_s8.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_maximum_s8.c \
	src/third_party/cmsis_nn/Source/BasicMathFunctions/arm_minimum_s8.c \
	src/third_party/cmsis_nn/Source/ConcatenationFunctions/arm_concatenation_s8_w.c \
	src/third_party/cmsis_nn/Source/ConcatenationFunctions/arm_concatenation_s8_x.c \
	src/third_party/cmsis_nn/Source/ConcatenationFunctions/arm_concatenation_s8_y.c \
	src/third_party/cmsis_nn/Source/ConcatenationFunctions/arm_concatenation_s8_z.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1_x_n_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1_x_n_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1x1_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1x1_s4_fast.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1x1_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_1x1_s8_fast.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_even_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_wrapper_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_wrapper_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_convolve_wrapper_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_fast_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_s4_opt.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s4.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_depthwise_conv_s8_core.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_row_offset_s8_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s4_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_mat_mult_kernel_s8_s16.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_nn_mat_mult_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_transpose_conv_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_transpose_conv_s8.c \
	src/third_party/cmsis_nn/Source/ConvolutionFunctions/arm_transpose_conv_wrapper_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_batch_matmul_s16.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_batch_matmul_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_get_buffer_sizes_s16.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_per_channel_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_s16.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_s4.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_fully_connected_wrapper_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_vector_sum_s8.c \
	src/third_party/cmsis_nn/Source/FullyConnectedFunctions/arm_vector_sum_s8_s64.c \
	src/third_party/cmsis_nn/Source/LSTMFunctions/arm_lstm_unidirectional_s16.c \
	src/third_party/cmsis_nn/Source/LSTMFunctions/arm_lstm_unidirectional_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_padded_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s4.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_depthwise_conv_nt_t_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_lstm_calculate_gate_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_lstm_calculate_gate_s8_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_lstm_step_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_lstm_step_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s4.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mul_core_1x_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mul_core_4x_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mult_nt_interleaved_t_even_s4.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s4.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8_s32.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_transpose_conv_row_s8_s32.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acc_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mul_result_acc_s8_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_per_ch_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s16_s16.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s4.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nn_vec_mat_mult_t_svdf_s8.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_nntables.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_q7_to_q15_with_offset.c \
	src/third_party/cmsis_nn/Source/NNSupportFunctions/arm_s8_to_s16_unordered_with_offset.c \
	src/third_party/cmsis_nn/Source/PadFunctions/arm_pad_s8.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_avgpool_get_buffer_sizes_s16.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_avgpool_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_avgpool_s16.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_avgpool_s8.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_max_pool_s16.c \
	src/third_party/cmsis_nn/Source/PoolingFunctions/arm_max_pool_s8.c \
	src/third_party/cmsis_nn/Source/ReshapeFunctions/arm_reshape_s8.c \
	src/third_party/cmsis_nn/Source/SVDFunctions/arm_svdf_get_buffer_sizes_s8.c \
	src/third_party/cmsis_nn/Source/SVDFunctions/arm_svdf_s8.c \
	src/third_party/cmsis_nn/Source/SVDFunctions/arm_svdf_state_s16_s8.c \
	src/third_party/cmsis_nn/Source/SoftmaxFunctions/arm_nn_softmax_common_s8.c \
	src/third_party/cmsis_nn/Source/SoftmaxFunctions/arm_softmax_s16.c \
	src/third_party/cmsis_nn/Source/SoftmaxFunctions/arm_softmax_s8.c \
	src/third_party/cmsis_nn/Source/SoftmaxFunctions/arm_softmax_s8_s16.c \
	src/third_party/cmsis_nn/Source/SoftmaxFunctions/arm_softmax_u8.c \
	src/third_party/cmsis_nn/Source/TransposeFunctions/arm_transpose_s8.c \

